
spring:
#  http:
#    multipart:
#      max-file-size:10MB
#      max-request-size=11MB
  jpa:
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/fiscus
    username: postgres
    password: 1213123
server:
  port: 8080


