
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment
    username: postgres
    password: purvesh
server:
  port: 8080